# Generated by Django 2.0.7 on 2018-07-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20180712_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingprogrammedisplay',
            name='short_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
