# Generated by Django 2.0.7 on 2018-10-30 14:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20180722_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepreference',
            name='an',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursepreference',
            name='semaine',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(53)]),
        ),
        migrations.AlterField(
            model_name='roompreference',
            name='an',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roompreference',
            name='semaine',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(53)]),
        ),
    ]
