# Generated by Django 2.1.2 on 2018-10-23 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20181022_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='edtversion',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Department'),
        ),
    ]
