# Generated by Django 2.1.2 on 2018-10-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_edtversion_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='abbrev',
            field=models.CharField(max_length=7),
        ),
    ]
