# Generated by Django 2.1.2 on 2018-10-26 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20181025_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='regen',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Department'),
        ),
    ]
