# Generated by Django 2.1.2 on 2018-10-31 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20181030_1440'),
        ('base', '0008_regen_department'),
    ]

    operations = [
    ]
