# Generated by Django 2.1.2 on 2018-11-01 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_merge_20181031_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='departments',
        ),
        migrations.AddField(
            model_name='roomtype',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Department'),
        ),
    ]
