# Generated by Django 2.1.2 on 2018-11-05 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20181102_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Department'),
        ),
    ]
