# Generated by Django 2.0.7 on 2018-11-11 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_period_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetype',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Department'),
        ),
    ]
