# Generated by Django 2.1.2 on 2019-01-14 10:23

from django.db import migrations, models
import django.db.models.deletion


def update_data(apps, schema_editor):
    """
    Associate each grouptype with all existing departments
    """
    Department = apps.get_model("base", "Department")
    GroupType = apps.get_model("base", "GroupType")
    Course = apps.get_model("base", "Course")
    Group = apps.get_model("base", "Group")

    departments = Department.objects.all()
    group_types = GroupType.objects.all()

    for index, department in enumerate(departments):
        if index == 0:
            # Associate existing group types with the first department
            group_types.update(department=department)
        else:
            # Create new group types
            for group_type in group_types:
                GroupType(name=group_type.name, department=department).save()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20181219_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptype',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Department'),
        ),
        migrations.RunPython(update_data),
    ]
