version: '3'

services:

  memcached:
    image: memcached
    ports:
      - "11211"

  db:
    restart: always
    image: postgres
    env_file:
      - ./docker/env/db.prod.env
    expose:
      - "5432"

  nginx:
    restart: always
    image: "nginx"
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - static-volume:/static
    links:
      - web

  redis:
    image: redis:latest

  web:
    #restart: always
    build: 
      context: .
      args:
        CONFIG: production
    env_file: 
      - ./docker/env/web.env
      - ./docker/env/db.prod.env
      - ./docker/env/web.prod.env
      - ./docker/env/secret.env
    environment:
      - DJANGO_SETTINGS_MODULE=FlOpEDT.settings.production
      - START_SERVER=${START_SERVER:-on}
      - DJANGO_LOADDATA
      - CONFIG=production
    expose:
      - "8000"
    volumes:
      - static-volume:/code/FlOpEDT/static
    depends_on:
      - db
      - redis      
    entrypoint: /code/docker/script/init.sh  

volumes:
  static-volume: