# Generated by Django 2.0.7 on 2018-07-12 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('last_name', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('for_name', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('nick_name', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('desc_author', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('date', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('header', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('positive_votes', models.PositiveIntegerField(default=0)),
                ('negative_votes', models.PositiveIntegerField(default=0)),
                ('id_acc', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('P', 'En attente'), ('A', 'Acceptée'), ('R', 'Rejetée')], default='P', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('abbrev', models.CharField(blank=True, max_length=10, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quote.QuoteType')),
            ],
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='quote.QuoteType'),
        ),
    ]
