# Generated by Django 2.0.7 on 2018-07-12 07:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolveRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_label', models.CharField(max_length=60)),
                ('start_week', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(53)])),
                ('start_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('end_week', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(53)])),
                ('end_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('log_file', models.CharField(default=None, max_length=1000, null=True)),
                ('iis_file', models.CharField(default=None, max_length=1000, null=True)),
            ],
        ),
    ]
