# Generated by Django 2.1.2 on 2018-10-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20181022_0910'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='departments',
            field=models.ManyToManyField(blank=True, to='base.Department'),
        ),
    ]
