# Generated by Django 2.0.7 on 2018-07-12 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('TTapp', '0002_auto_20180712_0749'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stabilize',
            name='tutor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Tutor'),
        ),
        migrations.AddField(
            model_name='stabilize',
            name='type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.CourseType'),
        ),
        migrations.AddField(
            model_name='simultaneouscourses',
            name='course1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course1', to='base.Course'),
        ),
        migrations.AddField(
            model_name='simultaneouscourses',
            name='course2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course2', to='base.Course'),
        ),
        migrations.AddField(
            model_name='reasonabledays',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Group'),
        ),
        migrations.AddField(
            model_name='reasonabledays',
            name='train_prog',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.TrainingProgramme'),
        ),
        migrations.AddField(
            model_name='reasonabledays',
            name='tutor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Tutor'),
        ),
        migrations.AddField(
            model_name='minnonpreferedslot',
            name='train_prog',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.TrainingProgramme'),
        ),
        migrations.AddField(
            model_name='minnonpreferedslot',
            name='tutor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Tutor'),
        ),
        migrations.AddField(
            model_name='minhalfdays',
            name='group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Group'),
        ),
        migrations.AddField(
            model_name='minhalfdays',
            name='module',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Module'),
        ),
        migrations.AddField(
            model_name='minhalfdays',
            name='tutor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Tutor'),
        ),
        migrations.AddField(
            model_name='limitedslotchoices',
            name='group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Group'),
        ),
        migrations.AddField(
            model_name='limitedslotchoices',
            name='module',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Module'),
        ),
        migrations.AddField(
            model_name='limitedslotchoices',
            name='possible_slots',
            field=models.ManyToManyField(related_name='limited_courses', to='base.Slot'),
        ),
        migrations.AddField(
            model_name='limitedslotchoices',
            name='train_prog',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.TrainingProgramme'),
        ),
        migrations.AddField(
            model_name='limitedslotchoices',
            name='tutor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Tutor'),
        ),
        migrations.AddField(
            model_name='limitedslotchoices',
            name='type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.CourseType'),
        ),
        migrations.AddField(
            model_name='limitcoursetypeperperiod',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Module'),
        ),
        migrations.AddField(
            model_name='limitcoursetypeperperiod',
            name='train_prog',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.TrainingProgramme'),
        ),
        migrations.AddField(
            model_name='limitcoursetypeperperiod',
            name='tutor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Tutor'),
        ),
        migrations.AddField(
            model_name='limitcoursetypeperperiod',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.CourseType'),
        ),
        migrations.AddField(
            model_name='avoidbothslots',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Group'),
        ),
        migrations.AddField(
            model_name='avoidbothslots',
            name='slot1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot1', to='base.Slot'),
        ),
        migrations.AddField(
            model_name='avoidbothslots',
            name='slot2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot2', to='base.Slot'),
        ),
        migrations.AddField(
            model_name='avoidbothslots',
            name='train_prog',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.TrainingProgramme'),
        ),
        migrations.AddField(
            model_name='avoidbothslots',
            name='tutor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Tutor'),
        ),
    ]
