# Generated by Django 2.1.1 on 2018-09-13 19:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('base', '0003_auto_20180722_1209'),
        ('TTapp', '0003_auto_20180712_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitedRoomChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveSmallIntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)])),
                ('year', models.PositiveSmallIntegerField(default=None, null=True)),
                ('weight', models.PositiveSmallIntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('comment', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Contrainte active?')),
                ('group', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Group')),
                ('module', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Module')),
                ('possible_rooms', models.ManyToManyField(related_name='limited_rooms', to='base.RoomGroup')),
                ('tutor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Tutor')),
                ('type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.CourseType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
