# Generated by Django 2.1.2 on 2018-11-02 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20181102_1101'),
        ('TTapp', '0004_limitedroomchoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='avoidbothslots',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Department'),
        ),
        migrations.AddField(
            model_name='limitcoursetypeperperiod',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Department'),
        ),
        migrations.AddField(
            model_name='limitedroomchoices',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Department'),
        ),
        migrations.AddField(
            model_name='limitedslotchoices',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Department'),
        ),
        migrations.AddField(
            model_name='minhalfdays',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Department'),
        ),
        migrations.AddField(
            model_name='minnonpreferedslot',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Department'),
        ),
        migrations.AddField(
            model_name='reasonabledays',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Department'),
        ),
        migrations.AddField(
            model_name='simultaneouscourses',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Department'),
        ),
        migrations.AddField(
            model_name='stabilize',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Department'),
        ),
    ]
