# Generated by Django 2.1.2 on 2018-11-08 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_period_department'),
        ('TTapp', '0005_auto_20181102_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitedroomchoices',
            name='train_prog',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.TrainingProgramme'),
        ),
        migrations.AddField(
            model_name='minhalfdays',
            name='train_prog',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.TrainingProgramme'),
        ),
        migrations.AddField(
            model_name='simultaneouscourses',
            name='train_prog',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.TrainingProgramme'),
        ),
    ]
