# Generated by Django 2.1.2 on 2018-12-19 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20181219_0858'),
        ('people', '0004_auto_20181219_0858'),
        ('TTapp', '0007_auto_20181113_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limitcoursetypeperperiod',
            name='tutor',
        ),
        migrations.RemoveField(
            model_name='reasonabledays',
            name='group',
        ),
        migrations.RemoveField(
            model_name='reasonabledays',
            name='tutor',
        ),
        migrations.AddField(
            model_name='limitcoursetypeperperiod',
            name='tutors',
            field=models.ManyToManyField(blank=True, related_name='Course_type_limits', to='people.Tutor'),
        ),
        migrations.AddField(
            model_name='reasonabledays',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='reasonable_day_constraints', to='base.Group'),
        ),
        migrations.AddField(
            model_name='reasonabledays',
            name='tutors',
            field=models.ManyToManyField(blank=True, related_name='reasonable_day_constraints', to='people.Tutor'),
        ),
        migrations.AddField(
            model_name='stabilize',
            name='fixed_days',
            field=models.ManyToManyField(blank=True, related_name='days_to_fix', to='base.Day'),
        ),
        migrations.AlterField(
            model_name='limitcoursetypeperperiod',
            name='module',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Module'),
        ),
        migrations.AlterField(
            model_name='minhalfdays',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Group'),
        ),
        migrations.AlterField(
            model_name='minhalfdays',
            name='module',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Module'),
        ),
    ]
