# Generated by Django 2.1.2 on 2019-01-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20181219_0858'),
        ('base', '0016_grouptype_department'),
        ('TTapp', '0008_auto_20181219_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minhalfdays',
            name='group',
        ),
        migrations.RemoveField(
            model_name='minhalfdays',
            name='module',
        ),
        migrations.RemoveField(
            model_name='minhalfdays',
            name='tutor',
        ),
        migrations.AddField(
            model_name='minhalfdays',
            name='groups',
            field=models.ManyToManyField(blank=True, to='base.Group'),
        ),
        migrations.AddField(
            model_name='minhalfdays',
            name='modules',
            field=models.ManyToManyField(blank=True, to='base.Module'),
        ),
        migrations.AddField(
            model_name='minhalfdays',
            name='tutors',
            field=models.ManyToManyField(blank=True, to='people.Tutor'),
        ),
    ]
